### PR TITLE
Fix sos_cmd's JSON results of all SOS value types

### PR DESCRIPTION
**Pull request by nichamon**
Commit bfc23855 introduced a bug that sos_cmd prints SOS_TYPE_BYTE_ARRAY
and SOS_TYPE_CHAR_ARRAY without double-quotes. The patch addresses the
bug and the formats of all SOS value types.

### CODE REVIEW

**Comment by nichamon** [comment]
@tom95858 @narategithub found a bug caused by the previous pull request that fixes the JSON format of SOS_TYPE_BYTE_ARRAY. The patch in the pull request uses a switch-case to make sure that the logic addresses all SOS types.

**Comment by narategithub** [comment]
@nichamon This looks OK to me.

**Comment by tom95858** [comment]
@nichamon, should I take this pull request?

**Comment by nichamon** [comment]
> should I take this pull request?

Yes, please!

**Pull request merged**
