### PR TITLE
Fix build problems on Ubuntu 20.4 & gcc 9.3.0

### PR DESCRIPTION
**Pull request by nichamon**

### CODE REVIEW

**Comment by nichamon** [comment]
@tom95858 I tried building SOS-5 on my Linux Mint machine, and I couldn't build it. The patches here fix the problem. I think gcc on Ubuntu wants us to explicitly link libraries if the source calls library symbols.

**Comment by tom95858** [comment]
All that this patch changes Mon is the path. I'm skeptical that the gcc on Ubuntu is so much different from the gcc on Centos. I think it might have more to do with automake and how paths for dependencies are resolved.

**Comment by nichamon** [comment]
@tom95858 The patch adds the path of `libsos` and `libsos_json`. Please note that the patch doesn't modify that path to `libdsos`. gcc on Ubuntu 20.4 needs us to specify the paths to all linked libraries. For example, `dsosql` uses APIs in both `libsos` and `libsos_json`. We need to specify the paths to both libraries on Ubuntu 20.4, but we don't need to do it to build Centos.

I also rebased on top of SOS-5 and resolved the conflicts.

We also need PR #53 to be able to build from a clean tree either on Centos or Ubuntu.

**Comment by tom95858** [comment]
@nichamon, there's something I don't understand. libdsos already includes libuuid and libsos, so I don't think we should have to do this. I realize it fixes the ubuntu build, but why? We need to get to the bottom of this and understand the why.

**Pull request merged**
